<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AutoMapper" Version="12.0.0" />
    <PackageVersion Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageVersion Include="CoreApiResponse" Version="1.0.1" />
    <PackageVersion Include="Firebase.Auth" Version="1.0.0" />
    <PackageVersion Include="FirebaseStorage.net" Version="1.0.3" />
    <PackageVersion Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageVersion Include="Google.Apis.Auth" Version="1.69.0" />
    <PackageVersion Include="MassTransit.Abstractions" Version="8.4.0" />
    <PackageVersion Include="MassTransit.RabbitMQ" Version="8.4.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="8.0.13" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
    <PackageVersion Include="MongoDB.Bson" Version="3.4.0" />
    <PackageVersion Include="MongoDB.Driver" Version="3.4.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageVersion Include="Swashbuckle.AspNetCore.Annotations" Version="7.3.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore.Filters" Version="8.0.2" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
    <PackageVersion Include="Treyt.Yarp.ReverseProxy.Swagger" Version="3.9.0" />
    <PackageVersion Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>
</Project>