services:
  apicontroller:
    image: api-gateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile

  breezydrive.users:
    image: breezydrive-userservice
    build:
      context: .
      dockerfile: BreezyDrive.UserServices/Dockerfile

  breezydrive.cars:
    image: breezydrive.carservice
    build:
      context: .
      dockerfile: BreezyDrive.CarServices/Dockerfile


  breezydrive.conversations:
    image: breezydrive.conversationservice
    build:
      context: .
      dockerfile: BreezyDrive.ConversationServices/Dockerfile
