<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" />
    <PackageReference Include="Firebase.Auth" />
    <PackageReference Include="FirebaseStorage.net" />
    <PackageReference Include="MassTransit.Abstractions" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Http" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="MongoDB.Bson" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Contracts\" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="C:\Users\Kaneki\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="C:\Users\Kaneki\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="C:\Users\Kaneki\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="C:\Users\Kaneki\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Library\Library.csproj" />
  </ItemGroup>
</Project>