<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.13" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.3.1" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BreezyDrive.BookingServices\BreezyDrive.BookingServices.csproj" />
      <ProjectReference Include="..\BreezyDrive.CarServices\BreezyDrive.CarServices.csproj" />
      <ProjectReference Include="..\BreezyDrive.ConversationServices\BreezyDrive.ConversationServices.csproj" />
      <ProjectReference Include="..\BreezyDrive.NotificationServices\BreezyDrive.NotificationServices.csproj" />
      <ProjectReference Include="..\BreezyDrive.UserServices\BreezyDrive.UserServices.csproj" />
    </ItemGroup>

</Project>
